// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $contact from "./routes/contact.tsx";
import * as $index from "./routes/index.tsx";
import * as $offer from "./routes/offer.tsx";
import * as $offer_id_ from "./routes/offer/[id].tsx";
import * as $project_id_ from "./routes/project/[id].tsx";
import * as $projects from "./routes/projects.tsx";
import * as $About from "./islands/About.tsx";
import * as $CompanyContact from "./islands/CompanyContact.tsx";
import * as $CompanyContactMap from "./islands/CompanyContactMap.tsx";
import * as $ConsentProvider from "./islands/ConsentProvider.tsx";
import * as $CookiePopup from "./islands/CookiePopup.tsx";
import * as $Feedbacks from "./islands/Feedbacks.tsx";
import * as $Footer from "./islands/Footer.tsx";
import * as $HeroHeader from "./islands/HeroHeader.tsx";
import * as $LatestProjects from "./islands/LatestProjects.tsx";
import * as $MainNavigation from "./islands/MainNavigation.tsx";
import * as $OfferDetails from "./islands/OfferDetails.tsx";
import * as $Offers from "./islands/Offers.tsx";
import * as $ProjectDetails from "./islands/ProjectDetails.tsx";
import * as $Projects from "./islands/Projects.tsx";
import * as $RootLayout from "./islands/RootLayout.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/contact.tsx": $contact,
    "./routes/index.tsx": $index,
    "./routes/offer.tsx": $offer,
    "./routes/offer/[id].tsx": $offer_id_,
    "./routes/project/[id].tsx": $project_id_,
    "./routes/projects.tsx": $projects,
  },
  islands: {
    "./islands/About.tsx": $About,
    "./islands/CompanyContact.tsx": $CompanyContact,
    "./islands/CompanyContactMap.tsx": $CompanyContactMap,
    "./islands/ConsentProvider.tsx": $ConsentProvider,
    "./islands/CookiePopup.tsx": $CookiePopup,
    "./islands/Feedbacks.tsx": $Feedbacks,
    "./islands/Footer.tsx": $Footer,
    "./islands/HeroHeader.tsx": $HeroHeader,
    "./islands/LatestProjects.tsx": $LatestProjects,
    "./islands/MainNavigation.tsx": $MainNavigation,
    "./islands/OfferDetails.tsx": $OfferDetails,
    "./islands/Offers.tsx": $Offers,
    "./islands/ProjectDetails.tsx": $ProjectDetails,
    "./islands/Projects.tsx": $Projects,
    "./islands/RootLayout.tsx": $RootLayout,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
