// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_feedbacks_all from "./routes/api/feedbacks/all.tsx";
import * as $api_offers_all from "./routes/api/offers/all.tsx";
import * as $api_offers_details_id_ from "./routes/api/offers/details/[id].tsx";
import * as $api_projects_all from "./routes/api/projects/all.tsx";
import * as $api_projects_details_id_ from "./routes/api/projects/details/[id].tsx";
import * as $contact from "./routes/contact.tsx";
import * as $index from "./routes/index.tsx";
import * as $offer from "./routes/offer.tsx";
import * as $offer_id_ from "./routes/offer/[id].tsx";
import * as $project_id_ from "./routes/project/[id].tsx";
import * as $projects from "./routes/projects.tsx";
import * as $layout_Footer from "./islands/layout/Footer.tsx";
import * as $layout_HeroHeader from "./islands/layout/HeroHeader.tsx";
import * as $layout_MainNavigation from "./islands/layout/MainNavigation.tsx";
import * as $layout_RootLayout from "./islands/layout/RootLayout.tsx";
import * as $main_PageContent from "./islands/main/PageContent.tsx";
import * as $pages_About from "./islands/pages/About.tsx";
import * as $pages_CompanyContact from "./islands/pages/CompanyContact.tsx";
import * as $pages_CompanyContactMap from "./islands/pages/CompanyContactMap.tsx";
import * as $pages_Feedbacks from "./islands/pages/Feedbacks.tsx";
import * as $pages_LatestProjects from "./islands/pages/LatestProjects.tsx";
import * as $pages_OfferDetails from "./islands/pages/OfferDetails.tsx";
import * as $pages_Offers from "./islands/pages/Offers.tsx";
import * as $pages_ProjectDetails from "./islands/pages/ProjectDetails.tsx";
import * as $pages_Projects from "./islands/pages/Projects.tsx";
import * as $popup_CookiePopup from "./islands/popup/CookiePopup.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/api/feedbacks/all.tsx": $api_feedbacks_all,
    "./routes/api/offers/all.tsx": $api_offers_all,
    "./routes/api/offers/details/[id].tsx": $api_offers_details_id_,
    "./routes/api/projects/all.tsx": $api_projects_all,
    "./routes/api/projects/details/[id].tsx": $api_projects_details_id_,
    "./routes/contact.tsx": $contact,
    "./routes/index.tsx": $index,
    "./routes/offer.tsx": $offer,
    "./routes/offer/[id].tsx": $offer_id_,
    "./routes/project/[id].tsx": $project_id_,
    "./routes/projects.tsx": $projects,
  },
  islands: {
    "./islands/layout/Footer.tsx": $layout_Footer,
    "./islands/layout/HeroHeader.tsx": $layout_HeroHeader,
    "./islands/layout/MainNavigation.tsx": $layout_MainNavigation,
    "./islands/layout/RootLayout.tsx": $layout_RootLayout,
    "./islands/main/PageContent.tsx": $main_PageContent,
    "./islands/pages/About.tsx": $pages_About,
    "./islands/pages/CompanyContact.tsx": $pages_CompanyContact,
    "./islands/pages/CompanyContactMap.tsx": $pages_CompanyContactMap,
    "./islands/pages/Feedbacks.tsx": $pages_Feedbacks,
    "./islands/pages/LatestProjects.tsx": $pages_LatestProjects,
    "./islands/pages/OfferDetails.tsx": $pages_OfferDetails,
    "./islands/pages/Offers.tsx": $pages_Offers,
    "./islands/pages/ProjectDetails.tsx": $pages_ProjectDetails,
    "./islands/pages/Projects.tsx": $pages_Projects,
    "./islands/popup/CookiePopup.tsx": $popup_CookiePopup,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
