// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $contact from "./routes/contact.tsx";
import * as $index from "./routes/index.tsx";
import * as $CompanyContact from "./islands/CompanyContact.tsx";
import * as $CompanyContactMap from "./islands/CompanyContactMap.tsx";
import * as $Feedbacks from "./islands/Feedbacks.tsx";
import * as $Footer from "./islands/Footer.tsx";
import * as $HeroHeader from "./islands/HeroHeader.tsx";
import * as $LatestProjects from "./islands/LatestProjects.tsx";
import * as $MainNavigation from "./islands/MainNavigation.tsx";
import * as $RootLayout from "./islands/RootLayout.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/contact.tsx": $contact,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/CompanyContact.tsx": $CompanyContact,
    "./islands/CompanyContactMap.tsx": $CompanyContactMap,
    "./islands/Feedbacks.tsx": $Feedbacks,
    "./islands/Footer.tsx": $Footer,
    "./islands/HeroHeader.tsx": $HeroHeader,
    "./islands/LatestProjects.tsx": $LatestProjects,
    "./islands/MainNavigation.tsx": $MainNavigation,
    "./islands/RootLayout.tsx": $RootLayout,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
